### ISSUE TITLE
🚨 [BUG] - Fix macOS Code Signing 

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#230]
### What happened?

We get the dreaded popup for our macOS release when it is downloaded and run:

<img width="259" alt="image" src="https://github.com/facebookincubator/TTPForge/assets/106620054/47d133e2-acb5-4044-a4ad-4e0d005c5ae0">
 

### Any suggestions for fixing this bug?

Update goreleaser config to sign mac builds

**Comment by l50** [comment]
Looked into this yesterday. We will need an apple developer account so that we can sign the binaries.

**Comment by d3sch41n** [comment]
[Issue Cleanup] Pruning this since existing install process is sufficient to mitigate the user-facing error, and a lot of other successful projects demonstrate the same behavior
