### ISSUE TITLE
Pre and post blocks?

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#25]
Do we want to build in a concept of pre- and post blocks? This would allow us to support cases such as:

1. I need two ec2 instances in two different regions and an s3 bucket before starting the TTP execution logic
2. I want to output the logs to an s3 bucket once the TTP finishes executing

Thoughts? Have we already captured this explicitly somewhere that I missed?

**Comment by d3sch41n** [comment]
* Post blocks use case is covered by `cleanup:` 
* Pre blocks use case will be addressed here: 

https://github.com/facebookincubator/TTPForge/issues/359
