### ISSUE TITLE
🚨 [BUG] - container action is broken

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#302]
### What happened?

Error is here: https://github.com/facebookincubator/TTPForge/actions/runs/6100875299/job/16556070829

### Any suggestions for fixing this bug?

Add a valid token to the repo options.

**Comment by d3sch41n** [comment]
@l50 what scopes are required for that action to work

**Comment by d3sch41n** [comment]
@l50 ok, I added all of the specified scopes as instructed. When I rerun the container action, there appears to be an issue with mage compilation/python:

https://github.com/facebookincubator/TTPForge/actions/runs/6161888869

```
163.9 	go get github.com/spf13/afero@v1.9.5
163.9 Error: error compiling magefiles
------
Dockerfile:67
--------------------
  66 |     # Setup Python environment, Go dependencies, and build
  67 | >>> RUN python3 -m venv $HOME/venv \
  68 | >>>     && . $HOME/venv/bin/activate \
  69 | >>>     && pip3 install --upgrade pip \
  70 | >>>     "setuptools>=${SETUP_TOOLS_VER}" \
  71 | >>>     pre-commit \
  72 | >>>     && pre-commit install-hooks \
  73 | >>>     && go install github.com/magefile/mage@latest \
  74 | >>>     && go install mvdan.cc/sh/v3/cmd/shfmt@latest \
  75 | >>>     && PATH=$HOME/venv/bin:$GOPATH/bin:$PATH \
  76 | >>>     && mage installDeps \
  77 | >>>     && mage \
  78 | >>>     && go mod tidy \
  79 | >>>     && go build -o ttpforge \
  80 | >>>     && rm ttpforge
  81 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m venv $HOME/venv     && . $HOME/venv/bin/activate     && pip3 install --upgrade pip     \"setuptools>=${SETUP_TOOLS_VER}\"     pre-commit     && pre-commit install-hooks     && go install github.com/magefile/mage@latest     && go install mvdan.cc/sh/v3/cmd/shfmt@latest     && PATH=$HOME/venv/bin:$GOPATH/bin:$PATH     && mage installDeps     && mage     && go mod tidy     && go build -o ttpforge     && rm ttpforge" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c python3 -m venv $HOME/venv     && . $HOME/venv/bin/activate     && pip3 install --upgrade pip     \"setuptools>=${SETUP_TOOLS_VER}\"     pre-commit     && pre-commit install-hooks     && go install github.com/magefile/mage@latest     && go install mvdan.cc/sh/v3/cmd/shfmt@latest     && PATH=$HOME/venv/bin:$GOPATH/bin:$PATH     && mage installDeps     && mage     && go mod tidy     && go build -o ttpforge     && rm ttpforge" did not complete successfully: exit code: 1
```

Could you take a look?

**Comment by l50** [comment]
This is a result of not landing the renovate bot updates - there have been updates to the go modules and we don't have them in main. I'll fix, but I need to understand why those haven't been landing - have you experienced a breaking update?

**Comment by d3sch41n** [comment]
> > @d3sch41n This is a result of not landing the renovate bot updates - there have been updates to the go modules and we don't have them in main. I'll fix, but I need to understand why those haven't been landing - have you experienced a breaking update?
> 
> I'd like to understand the mechanism of action here. Which renovate PR specifically, had it landed, would have prevented this from breaking? Could you link it?

@l50 and I sync'd offline - going to investigate `go mod tidy` race conditions in container builds

**Comment by d3sch41n** [comment]
Current status - escalating to ensure that this repo is linked to the corresponding package so that our action will have permissions to push to it

**Comment by d3sch41n** [comment]
Apparently GITHUB_TOKEN just works in spite of the repo not being linked? 🙃 Will leave open till I figure out why

 <img width="654" alt="image" src="https://github.com/facebookincubator/TTPForge/assets/106620054/3bc10c5b-276a-4bc7-ae29-1883d218fba6">

**Comment by l50** [comment]
It's linked: 
![Screenshot 2023-09-18 at 12 19 32 PM](https://github.com/facebookincubator/TTPForge/assets/4031126/b8b969f1-10b0-4c68-ae4d-733c84dd54c5)

**Comment by l50** [comment]
Issue appears to be resolved, closing.

**Comment by d3sch41n** [comment]
> > Apparently GITHUB_TOKEN just works in spite of the repo not being linked? 🙃 Will leave open till I figure out why
> > <img alt="image" width="654" src="https://user-images.githubusercontent.com/106620054/268162176-3bc10c5b-276a-4bc7-ae29-1883d218fba6.png">
> 
> It's linked: ![Screenshot 2023-09-18 at 12 19 32 PM](https://user-images.githubusercontent.com/4031126/268738151-b8b969f1-10b0-4c68-ae4d-733c84dd54c5.png)

Weird - did you do something to make it succeed? I thought we were both getting "Permission denied" to link it - would be good to understand why it worked

**Comment by d3sch41n** [comment]
Leaving open pending confirmation of root cause:

https://github.com/facebookincubator/TTPForge/issues/347#issue-1904102326

**Comment by d3sch41n** [comment]
Container deprecated in:

https://github.com/facebookincubator/TTPForge/pull/446
