### ISSUE TITLE
💡 [REQUEST] - Add Support for `choices` in Argument Specifications

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#409]
### Summary

Goal is to support this setup - allow only a fixed set of values for an argument, and error if any other values are provided:

```
args:
  - name: dns_record_type
     choices:
       - "TXT"
       - "A"
       - "AAAA" 
 ``` 

For the TTP above, this should give no error:

```
ttpforge run path/to/ttp.yaml --arg dns_record_type="AAAA"
```

And this should give an error ("invalid value for argument "dns_record_type" - allowed choices are...")

```
ttpforge run path/to/ttp.yaml --arg dns_record_type="totally_not_a_valid_choice"
```

There are some subtleties that will need to be checked:

```
* If a `default` value is specified for the argument, it must be one of the `choices` 
* all of the `choices` must be valid instance of the arguments type (e.g. can't have "yoyoyo" be a choice for an argument with `type: int`) 
```

This would be implemented by adding a `choices` field here: 

https://github.com/facebookincubator/TTPForge/blob/main/pkg/args/spec.go#L30 

### Basic Example

See above

### Drawbacks

Extra syntactic sugar, but useful for catching user errors early

**Comment by inesusvet** [comment]
This existing issue to cobra seems relevant
https://github.com/spf13/cobra/issues/1006#issuecomment-569276097

**Comment by d3sch41n** [comment]
> This existing issue to cobra seems relevant [spf13/cobra#1006 (comment)](https://github.com/spf13/cobra/issues/1006#issuecomment-569276097)

Hey! So actually all of these arguments map to the same single cobra argument, `--arg`, from `cmd/run.go` 

```
	runCmd.Flags().StringArrayVarP(&argsList, "arg", "a", []string{}, "variable input mapping for args to be used in place of inputs defined in each ttp file")
```

So the user runs `ttpforge run foo/bar/baz.yaml --arg first_arg=foo --arg second_arg=bar` and that ends up in `argList` as `["first_arg=foo", "second_arg=bar"]` - we then parse out and validate the arguments using the code in `pkg/args/spec.go`   

So this `choices` feature will operate at the YAML level  rather than the pre-compiled Golang level (like that cobra issue was referencing) - let me know if that helps clarify!

**Comment by d3sch41n** [comment]
Closed by PR https://github.com/facebookincubator/TTPForge/pull/411
