### ISSUE TITLE
💡 [REQUEST] - Finish Recursive Copying Support for `copy_path` 

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#422]
### Summary

The cleanest way to handle copying both files and directories in the `copy_path` action is to use this package:

https://pkg.go.dev/github.com/otiai10/copy 

You'll need to add it as a dependency using the previously-shared instructions. 

Note that this package supports some fancy concurrent copying mechanics - we don't want those, so just leave these config options as the default (disabled):

<img width="811" alt="image" src="https://github.com/facebookincubator/TTPForge/assets/106620054/1da4566e-58aa-42eb-bfc8-28d73894f623">

### Basic Example

N/A 

### Drawbacks

The principal challenge will be that afero doesn't support this library. There doesn't seem to be a good way
to copy directories with afero (correct me if I am wrong) so you'll want to restructure the copy_path tests to instead use the OS file system and work within a dynamically created temporary directory that gets refreshed on each test case. Use [MkdirTemp](https://pkg.go.dev/os#MkdirTemp ) for this purpose, with the following nuances:

1. place your call to mkdirtemp inside of the test case for loop
2. make sure that you `defer` removal of the temp directory immediately after creating it

**Comment by d3sch41n** [comment]
@d0n601  closed in https://github.com/facebookincubator/TTPForge/pull/451

**Comment by d0n601** [comment]
https://github.com/facebookincubator/TTPForge/pull/468

**Comment by d0n601** [comment]
https://github.com/facebookincubator/TTPForge/pull/468
